# Generated by Django 2.1.5 on 2019-03-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=90)),
                ('name', models.CharField(max_length=90)),
                ('amount', models.IntegerField()),
                ('date', models.CharField(max_length=10)),
            ],
        ),
    ]
