# Generated by Django 2.1.5 on 2019-03-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sell', '0006_auto_20190302_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer_demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('buyer_name', models.CharField(max_length=90)),
                ('crop_name', models.CharField(max_length=90)),
                ('amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('bought', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='farmer_crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('farmer_name', models.CharField(max_length=90)),
                ('crop_name', models.CharField(max_length=90)),
                ('amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('bought', models.CharField(max_length=90)),
            ],
        ),
    ]
