# Generated by Django 2.1.5 on 2019-03-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizer_shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project',
        ),
    ]
