# Generated by Django 2.1.5 on 2019-03-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizer_shop', '0004_fertilizer_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='buyer',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
