# Generated by Django 2.1.5 on 2019-03-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizer_shop', '0006_auto_20190302_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='fertilizer_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('buyer', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='fertilizer',
        ),
    ]
